GET http://localhost:3000/api/admin/orders

###

POST http://localhost:3000/api/session/verify
Content-Type: application/json

{
    "sessionId": "cs_test_a16MzFPn8Mgbm44UrZ5WnB0oLZQKvIpXAgWY8f2hrj7BFWY3roqQtko5uq"
}
